apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- crs.yaml

configMapGenerator:
- name: "${CLUSTER_NAME}-crs-kube-vip"
  options:
    disableNameSuffixHash: true
  files:
  - data=kube-vip.yaml
- name: "${CLUSTER_NAME}-crs-kube-vip-rbac"
  options:
    disableNameSuffixHash: true
  files:
  - data=kube-vip-rbac.yaml

patches:
- patch: |-
    kind: Cluster
    metadata:
      name: not-used
      labels:
        kube-vip: "${CLUSTER_NAME}-crs-kube-vip"
  target:
    kind: Cluster
- patch: |
    - op: add
      path: /spec/kubeadmConfigSpec/preKubeadmCommands/-
      value: |-
             GATEWAY_IP=$(curl https://metadata.platformequinix.com/metadata | jq -r ".network.addresses[] | select(.public == false) | .gateway")
             ip route add 169.254.255.1 via $$GATEWAY_IP
             ip route add 169.254.255.2 via $$GATEWAY_IP
  target:
    kind: KubeadmControlPlane
- patch: |
    - op: add
      path: /spec/template/spec/preKubeadmCommands/-
      value: |-
             GATEWAY_IP=$(curl https://metadata.platformequinix.com/metadata | jq -r ".network.addresses[] | select(.public == false) | .gateway")
             ip route add 169.254.255.1 via $$GATEWAY_IP
             ip route add 169.254.255.2 via $$GATEWAY_IP
  target:
    kind: KubeadmConfigTemplate
