apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- crs.yaml

configMapGenerator:
- name: "${CLUSTER_NAME}-crs-kube-vip"
  options:
    disableNameSuffixHash: true
  files:
  - data=kube-vip.yaml
- name: "${CLUSTER_NAME}-crs-kube-vip-rbac"
  options:
    disableNameSuffixHash: true
  files:
  - data=kube-vip-rbac.yaml

patches:
- patch: |-
    kind: Cluster
    metadata:
      name: not-used
      labels:
        kube-vip: "${CLUSTER_NAME}-crs-kube-vip"
  target:
    kind: Cluster
