apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base-v1beta1

components:
  - ../../components/providerid
  - ../../components/external-cloud-provider
  - ../../components/preKubeadmCommands
  - ../../components/kubevip-static
  - ../../components/cpem-no-eip
#  - ../../components/hacky-eip-workaround
  - ../../components/crs-calico
  - ../../components/crs-kube-vip
