apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- patch: |-
    kind: KubeadmControlPlane
    metadata:
      name: not-used
    spec:
      kubeadmConfigSpec:
        clusterConfiguration:
          apiServer:
            extraArgs:
              cloud-provider: external
          controllerManager:
            extraArgs:
              cloud-provider: external
        initConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              cloud-provider: external
        joinConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              cloud-provider: external
  target:
    kind: KubeadmControlPlane
- patch: |-
    kind: KubeadmConfigTemplate
    metadata:
        name: not-used
    spec:
        template:
            spec:
                joinConfiguration:
                    nodeRegistration:
                        kubeletExtraArgs:
                            cloud-provider: external
  target:
    kind: KubeadmConfigTemplate
