---
# ClusterResourceSet object with
# a selector that targets all the Cluster with label cni=${CLUSTER_NAME}-crs-calico
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name:  "${CLUSTER_NAME}-crs-calico"
spec:
  strategy: ApplyOnce
  clusterSelector:
    matchLabels:
      cni: "${CLUSTER_NAME}-crs-calico"
  resources:
    - name: "${CLUSTER_NAME}-crs-calico"
      kind: ConfigMap