apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- crs.yaml

configMapGenerator:
- name: "${CLUSTER_NAME}-crs-calico"
  options:
    disableNameSuffixHash: true
  files:
  - data=calico.yaml

patches:
- patch: |-
    kind: Cluster
    metadata:
      name: not-used
      labels:
        cni: "${CLUSTER_NAME}-crs-calico"
  target:
    kind: Cluster
