apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- patch: |-
    kind: KubeadmControlPlane
    metadata:
      name: not-used
    spec:
      kubeadmConfigSpec:
        initConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              provider-id: "equinixmetal://{{ `{{ v1.instance_id }}` }}"
        joinConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              provider-id: "equinixmetal://{{ `{{ v1.instance_id }}` }}"
  target:
    kind: KubeadmControlPlane
- patch: |-
    kind: KubeadmConfigTemplate
    metadata:
      name: not-used
    spec:
      template:
        spec:
          joinConfiguration:
            nodeRegistration:
              kubeletExtraArgs:
                provider-id: "equinixmetal://{{ `{{ v1.instance_id }}` }}"
  target:
    kind: KubeadmConfigTemplate
