apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- patch: |-
    kind: KubeadmControlPlane
    metadata:
      name: not-used
    spec:
      kubeadmConfigSpec:
        preKubeadmCommands:
        - |
          sed -ri '/\sswap\s/s/^#?/#/' /etc/fstab
          swapoff -a
          mount -a
          cat <<EOF > /etc/modules-load.d/containerd.conf
          overlay
          br_netfilter
          EOF
          modprobe overlay
          modprobe br_netfilter
          cat <<EOF > /etc/sysctl.d/99-kubernetes-cri.conf
          net.bridge.bridge-nf-call-iptables  = 1
          net.ipv4.ip_forward                 = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          EOF
          sysctl --system
          apt-get -y update
          DEBIAN_FRONTEND=noninteractive apt-get install -y apt-transport-https curl
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
          echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
          apt-get update -y
          TRIMMED_KUBERNETES_VERSION=$(echo {{ .kubernetesVersion }} | sed 's/\./\\./g' | sed 's/^v//')
          RESOLVED_KUBERNETES_VERSION=$(apt-cache policy kubelet | awk -v VERSION=$${TRIMMED_KUBERNETES_VERSION} '$1~ VERSION { print $1 }' | head -n1)
          apt-get install -y ca-certificates socat jq ebtables apt-transport-https cloud-utils prips containerd kubelet=$${RESOLVED_KUBERNETES_VERSION} kubeadm=$${RESOLVED_KUBERNETES_VERSION} kubectl=$${RESOLVED_KUBERNETES_VERSION}
          systemctl daemon-reload
          systemctl enable containerd
          systemctl start containerd
  target:
    kind: KubeadmControlPlane

# Copy the preKubeadmCommands from the KubeadmControlPlane to the KubeadmConfigTemplate to avoid potential drift
replacements:
- source:
    kind: KubeadmControlPlane
    fieldPath: spec.kubeadmConfigSpec.preKubeadmCommands
  targets:
    - select:
        kind: KubeadmConfigTemplate
      fieldPaths:
        - spec.template.spec.preKubeadmCommands
      options:
        create: true
